# deliveryconfirmation-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: deliveryconfirmation-service-service
spec:
  type: NodePort
  selector:
    app: deliveryconfirmation-service
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30004
