# orderconfirmation-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: orderconfirmation-service-service
spec:
  type: NodePort
  selector:
    app: orderconfirmation-service
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30003
