# weborder-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weborder-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weborder-service
  template:
    metadata:
      labels:
        app: weborder-service
    spec:
      containers:
      - name: weborder-service
        image: weborder-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
