# weborder-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: weborder-service-service
spec:
  type: NodePort
  selector:
    app: weborder-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
